export default interface IIncomeVehicleList {
  id?: number,
  date_init: null | string,
  mecanic_id: null | number,
  type_vehicle: null | string,
  brand: null | string,
  pay_labor: null | number,
  plate: null | string,
  value_labor: null | number,
  value_parts: null | number,
  total_costs: null | number,
  paid_labor: null | number,
  date_pay_labor: null | string,
  utilites: null | number,
}
